export enum InputType {
  button = "button",
  checkbox = "checkbox",
  color = "color",
  date = "date",
  datetimelocal = "datetime-local",
  email = "email",
  file = "file",
  hidden = "hidden",
  image = "image",
  month = "month",
  number = "number",
  password = "password",
  radio = "radio",
  range = "range",
  reset = "reset",
  search = "search",
  submit = "submit",
  tel = "tel",
  text = "text",
  time = "time",
  url = "url",
  week = "week",
  select = "select",
}

export enum CountryEnum {
  EUROPE = "EUROPE",
  JAPAN = "JAPAN",
  UK = "UNITED KINGDOM",
  USA = "U.S America",
  Latin = "Latin America",
}
